/*Author: Purnanand Wasave*/

INSERT INTO EMPLOYEES (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'John', 32, 'London', 150000 );

INSERT INTO EMPLOYEES (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (2, 'Lisa', 26, 'Moscow', 200000 );

INSERT INTO EMPLOYEES (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'Roy', 28, 'Paris', 180000 );

INSERT INTO EMPLOYEES (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Taylor', 24, 'Washington', 220000 );

INSERT INTO EMPLOYEES (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Selena', 22, 'Los Angeles', 183000);

INSERT INTO EMPLOYEES (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'David', 29, 'Manchester', 230000 );
